// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nc_recordshop_backend;

#nullable disable

namespace nc_recordshop_backend.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260506141855_mig12")]
    partial class mig12
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("nc_recordshop_backend.Model.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("TrackList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Artist = "Pink Floyd",
                            Description = "The eigth albumn by Pink Floyd, it's a concept album exploring themes of conflict, greed, time",
                            Genre = "Progressive Rock",
                            Name = "The Dark Side of the Moon",
                            Quantity = 3,
                            ReleaseDate = new DateOnly(1973, 3, 1),
                            TrackList = "[\"Speak To Me\",\"Breathe\",\"On The Run\",\"Time\",\"The Great Gig In The Sky\",\"Money\",\"Us And Them\",\"Any Colour You Like\",\"Brain Damage\",\"Eclipse\"]"
                        },
                        new
                        {
                            Id = 2,
                            Artist = "Michael Jackson",
                            Description = "One of the best selling albums of all time",
                            Genre = "Dance-pop",
                            Name = "Bad",
                            Quantity = 0,
                            ReleaseDate = new DateOnly(1987, 8, 31),
                            TrackList = "[\"I Just Can\\u0027t Stop Loving You\",\"Bad\",\"The Way You Make Me Feel\",\"Man in the Mirror\",\"Dirty Diana\",\"Another Part of Me\",\"Smooth Criminal\",\"Leave Me Alone\",\"Liberian Girl\"]"
                        },
                        new
                        {
                            Id = 3,
                            Artist = "Adele",
                            Description = "Named after Adele's age during it's production",
                            Genre = "Pop",
                            Name = "21",
                            Quantity = 17,
                            ReleaseDate = new DateOnly(2011, 1, 24),
                            TrackList = "[\"Rolling in the Deep\",\"Someone like You\",\"Set Fire to the Rain\",\"Rumour Has It\",\"Turning Tables\"]"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
