// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nc_recordshop_backend;

#nullable disable

namespace nc_recordshop_backend.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260708091513_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("nc_recordshop_backend.Model.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("TrackList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Artist = "Pink Floyd",
                            Description = "The eighth album by Pink Floyd, it's a concept album exploring themes of conflict, greed, and time.",
                            Genre = "Progressive Rock",
                            Name = "The Dark Side of the Moon",
                            Quantity = 3,
                            ReleaseDate = new DateOnly(1973, 3, 1),
                            TrackList = "[\"Speak to Me\",\"Breathe (In the Air)\",\"On the Run\",\"Time\",\"The Great Gig in the Sky\",\"Money\",\"Us and Them\",\"Any Colour You Like\",\"Brain Damage\",\"Eclipse\"]"
                        },
                        new
                        {
                            Id = 2,
                            Artist = "Michael Jackson",
                            Description = "One of the best-selling albums of all time and Michael Jackson's seventh studio album.",
                            Genre = "Pop, R&B, Funk",
                            Name = "Bad",
                            Quantity = 0,
                            ReleaseDate = new DateOnly(1987, 8, 31),
                            TrackList = "[\"Bad\",\"The Way You Make Me Feel\",\"Speed Demon\",\"Liberian Girl\",\"Just Good Friends\",\"Another Part of Me\",\"Man in the Mirror\",\"I Just Can\\u0027t Stop Loving You\",\"Dirty Diana\",\"Smooth Criminal\",\"Leave Me Alone\"]"
                        },
                        new
                        {
                            Id = 3,
                            Artist = "Adele",
                            Description = "Named after Adele's age during its production, this is her second studio album.",
                            Genre = "Pop, Soul",
                            Name = "21",
                            Quantity = 17,
                            ReleaseDate = new DateOnly(2011, 1, 24),
                            TrackList = "[\"Rolling in the Deep\",\"Rumour Has It\",\"Turning Tables\",\"Don\\u0027t You Remember\",\"Set Fire to the Rain\",\"He Won\\u0027t Go\",\"Take It All\",\"I\\u0027ll Be Waiting\",\"One and Only\",\"Lovesong\",\"Someone Like You\"]"
                        },
                        new
                        {
                            Id = 4,
                            Artist = "Michael Jackson",
                            Description = "The best-selling album of all time by Michael Jackson.",
                            Genre = "Pop, Post-Disco, R&B, Rock",
                            Name = "Thriller",
                            Quantity = 10,
                            ReleaseDate = new DateOnly(1982, 11, 29),
                            TrackList = "[\"Wanna Be Startin\\u0027 Somethin\\u0027\",\"Baby Be Mine\",\"The Girl Is Mine\",\"Thriller\",\"Beat It\",\"Billie Jean\",\"Human Nature\",\"P.Y.T. (Pretty Young Thing)\",\"The Lady in My Life\"]"
                        },
                        new
                        {
                            Id = 5,
                            Artist = "AC/DC",
                            Description = "The seventh studio album by Australian rock band AC/DC.",
                            Genre = "Hard Rock",
                            Name = "Back in Black",
                            Quantity = 10,
                            ReleaseDate = new DateOnly(1980, 7, 25),
                            TrackList = "[\"Hells Bells\",\"Shoot to Thrill\",\"What Do You Do for Money Honey\",\"Given the Dog a Bone\",\"Let Me Put My Love Into You\",\"Back in Black\",\"You Shook Me All Night Long\",\"Have a Drink on Me\",\"Shake a Leg\",\"Rock and Roll Ain\\u0027t Noise Pollution\"]"
                        },
                        new
                        {
                            Id = 6,
                            Artist = "Whitney Houston",
                            Description = "Soundtrack to the 1992 film, primarily featuring Whitney Houston.",
                            Genre = "R&B, Pop",
                            Name = "The Bodyguard",
                            Quantity = 10,
                            ReleaseDate = new DateOnly(1992, 11, 17),
                            TrackList = "[\"I Will Always Love You\",\"I Have Nothing\",\"I\\u0027m Every Woman\",\"Run to You\",\"Queen of the Night\",\"Jesus Loves Me\",\"Even If My Heart Would Break\",\"Someday (I\\u0027m Coming Back)\",\"It\\u0027s Gonna Be a Lovely Day\",\"(What\\u0027s So Funny \\u0027Bout) Peace, Love, and Understanding\",\"Waiting for You\",\"Trust in Me\",\"Theme from The Bodyguard\"]"
                        },
                        new
                        {
                            Id = 7,
                            Artist = "Fleetwood Mac",
                            Description = "The eleventh studio album by British-American rock band Fleetwood Mac.",
                            Genre = "Soft Rock",
                            Name = "Rumours",
                            Quantity = 10,
                            ReleaseDate = new DateOnly(1977, 2, 4),
                            TrackList = "[\"Second Hand News\",\"Dreams\",\"Never Going Back Again\",\"Don\\u0027t Stop\",\"Go Your Own Way\",\"Songbird\",\"The Chain\",\"You Make Loving Fun\",\"I Don\\u0027t Want to Know\",\"Oh Daddy\",\"Gold Dust Woman\"]"
                        },
                        new
                        {
                            Id = 8,
                            Artist = "Bee Gees",
                            Description = "The soundtrack album from the 1977 film.",
                            Genre = "Disco",
                            Name = "Saturday Night Fever",
                            Quantity = 10,
                            ReleaseDate = new DateOnly(1977, 11, 15),
                            TrackList = "[\"Stayin\\u0027 Alive\",\"How Deep Is Your Love\",\"Night Fever\",\"More Than a Woman\",\"If I Can\\u0027t Have You\",\"A Fifth of Beethoven\",\"More Than a Woman (Tavares)\",\"Manhattan Skyline\",\"Calypso Breakdown\",\"Night on Disco Mountain\",\"Open Sesame\",\"Jive Talkin\\u0027\",\"You Should Be Dancing\",\"Boogie Shoes\",\"Salsation\",\"K-Jee\",\"Disco Inferno\"]"
                        },
                        new
                        {
                            Id = 9,
                            Artist = "Shania Twain",
                            Description = "The third studio album by Canadian singer Shania Twain.",
                            Genre = "Country Pop",
                            Name = "Come On Over",
                            Quantity = 10,
                            ReleaseDate = new DateOnly(1997, 11, 4),
                            TrackList = "[\"Man! I Feel Like a Woman!\",\"I\\u0027m Holdin\\u0027 On to Love (To Save My Life)\",\"Love Gets Me Every Time\",\"Don\\u0027t Be Stupid (You Know I Love You)\",\"From This Moment On\",\"Come On Over\",\"When\",\"Whatever You Do! Don\\u0027t!\",\"If You Wanna Touch Her, Ask!\",\"You\\u0027re Still the One\",\"Honey, I\\u0027m Home\",\"That Don\\u0027t Impress Me Much\",\"Black Eyes, Blue Tears\",\"I Won\\u0027t Leave You Lonely\",\"Rock This Country!\",\"You\\u0027ve Got a Way\"]"
                        },
                        new
                        {
                            Id = 10,
                            Artist = "Meat Loaf",
                            Description = "The 1977 debut album by American rock singer Meat Loaf.",
                            Genre = "Hard Rock, Progressive Rock",
                            Name = "Bat Out of Hell",
                            Quantity = 10,
                            ReleaseDate = new DateOnly(1977, 10, 21),
                            TrackList = "[\"Bat Out of Hell\",\"You Took the Words Right Out of My Mouth (Hot Summer Night)\",\"Heaven Can Wait\",\"All Revved Up with No Place to Go\",\"Two Out of Three Ain\\u0027t Bad\",\"Paradise by the Dashboard Light\",\"For Crying Out Loud\"]"
                        },
                        new
                        {
                            Id = 11,
                            Artist = "Eagles",
                            Description = "The fifth studio album by American rock band Eagles.",
                            Genre = "Rock",
                            Name = "Hotel California",
                            Quantity = 10,
                            ReleaseDate = new DateOnly(1976, 12, 8),
                            TrackList = "[\"Hotel California\",\"New Kid in Town\",\"Life in the Fast Lane\",\"Wasted Time\",\"Wasted Time (Reprise)\",\"Victim of Love\",\"Pretty Maids All in a Row\",\"Try and Love Again\",\"The Last Resort\"]"
                        },
                        new
                        {
                            Id = 12,
                            Artist = "The Beatles",
                            Description = "The eighth studio album by the English rock band the Beatles.",
                            Genre = "Psychedelic Rock",
                            Name = "Sgt. Pepper's Lonely Hearts Club Band",
                            Quantity = 10,
                            ReleaseDate = new DateOnly(1967, 5, 26),
                            TrackList = "[\"Sgt. Pepper\\u0027s Lonely Hearts Club Band\",\"With a Little Help from My Friends\",\"Lucy in the Sky with Diamonds\",\"Getting Better\",\"Fixing a Hole\",\"She\\u0027s Leaving Home\",\"Being for the Benefit of Mr. Kite!\",\"Within You Without You\",\"When I\\u0027m Sixty-Four\",\"Lovely Rita\",\"Good Morning Good Morning\",\"Sgt. Pepper\\u0027s Lonely Hearts Club Band (Reprise)\",\"A Day in the Life\"]"
                        },
                        new
                        {
                            Id = 13,
                            Artist = "Led Zeppelin",
                            Description = "The untitled fourth studio album by the English rock band Led Zeppelin.",
                            Genre = "Hard Rock, Heavy Metal",
                            Name = "Led Zeppelin IV",
                            Quantity = 10,
                            ReleaseDate = new DateOnly(1971, 11, 8),
                            TrackList = "[\"Black Dog\",\"Rock and Roll\",\"The Battle of Evermore\",\"Stairway to Heaven\",\"Misty Mountain Hop\",\"Four Sticks\",\"Going to California\",\"When the Levee Breaks\"]"
                        },
                        new
                        {
                            Id = 14,
                            Artist = "Bruce Springsteen",
                            Description = "The seventh studio album by American rock singer-songwriter Bruce Springsteen.",
                            Genre = "Heartland Rock",
                            Name = "Born in the U.S.A.",
                            Quantity = 10,
                            ReleaseDate = new DateOnly(1984, 6, 4),
                            TrackList = "[\"Born in the U.S.A.\",\"Cover Me\",\"Darlington County\",\"Working on the Highway\",\"Downbound Train\",\"I\\u0027m on Fire\",\"No Surrender\",\"Bobby Jean\",\"I\\u0027m Goin\\u0027 Down\",\"Glory Days\",\"Dancing in the Dark\",\"My Hometown\"]"
                        },
                        new
                        {
                            Id = 15,
                            Artist = "Alanis Morissette",
                            Description = "The third studio album by Canadian singer Alanis Morissette.",
                            Genre = "Alternative Rock",
                            Name = "Jagged Little Pill",
                            Quantity = 10,
                            ReleaseDate = new DateOnly(1995, 6, 13),
                            TrackList = "[\"All I Really Want\",\"You Oughta Know\",\"Perfect\",\"Hand in My Pocket\",\"Right Through You\",\"Forgiven\",\"You Learn\",\"Head over Feet\",\"Mary Jane\",\"Ironic\",\"Not the Doctor\",\"Wake Up\"]"
                        },
                        new
                        {
                            Id = 16,
                            Artist = "The Beatles",
                            Description = "A compilation album by the English rock band the Beatles.",
                            Genre = "Rock",
                            Name = "1",
                            Quantity = 10,
                            ReleaseDate = new DateOnly(2000, 11, 13),
                            TrackList = "[\"Love Me Do\",\"From Me to You\",\"She Loves You\",\"I Want to Hold Your Hand\",\"Can\\u0027t Buy Me Love\",\"A Hard Day\\u0027s Night\",\"I Feel Fine\",\"Eight Days a Week\",\"Ticket to Ride\",\"Help!\",\"Yesterday\",\"Day Tripper\",\"We Can Work It Out\",\"Paperback Writer\",\"Yellow Submarine\",\"Eleanor Rigby\",\"Penny Lane\",\"All You Need Is Love\",\"Hello, Goodbye\",\"Lady Madonna\",\"Hey Jude\",\"Get Back\",\"The Ballad of John and Yoko\",\"Something\",\"Come Together\",\"Let It Be\",\"The Long and Winding Road\"]"
                        },
                        new
                        {
                            Id = 17,
                            Artist = "Celine Dion",
                            Description = "The fourth English-language studio album by Canadian singer Celine Dion.",
                            Genre = "Pop",
                            Name = "Falling into You",
                            Quantity = 10,
                            ReleaseDate = new DateOnly(1996, 3, 11),
                            TrackList = "[\"It\\u0027s All Coming Back to Me Now\",\"Because You Loved Me\",\"Falling into You\",\"Make You Happy\",\"Seduces Me\",\"All by Myself\",\"Declaration of Love\",\"(You Make Me Feel Like) A Natural Woman\",\"Dreamin\\u0027 of You\",\"I Love You\",\"If That\\u0027s What It Takes\",\"I Don\\u0027t Know\",\"River Deep, Mountain High\",\"Call the Man\",\"Fly\"]"
                        },
                        new
                        {
                            Id = 18,
                            Artist = "Celine Dion",
                            Description = "The fifth English-language studio album by Canadian singer Celine Dion.",
                            Genre = "Pop",
                            Name = "Let's Talk About Love",
                            Quantity = 10,
                            ReleaseDate = new DateOnly(1997, 11, 14),
                            TrackList = "[\"The Reason\",\"Immortality\",\"Treat Her Like a Lady\",\"Why Oh Why\",\"Love Is on the Way\",\"Tell Him\",\"Where Is the Love\",\"When I Need You\",\"Miles to Go (Before I Sleep)\",\"Us\",\"Just a Little Bit of Love\",\"My Heart Will Go On\",\"I Hate You Then I Love You\",\"To Love You More\",\"Let\\u0027s Talk About Love\"]"
                        },
                        new
                        {
                            Id = 19,
                            Artist = "The Beatles",
                            Description = "The eleventh studio album by the English rock band the Beatles.",
                            Genre = "Rock",
                            Name = "Abbey Road",
                            Quantity = 10,
                            ReleaseDate = new DateOnly(1969, 9, 26),
                            TrackList = "[\"Come Together\",\"Something\",\"Maxwell\\u0027s Silver Hammer\",\"Oh! Darling\",\"Octopus\\u0027s Garden\",\"I Want You (She\\u0027s So Heavy)\",\"Here Comes the Sun\",\"Because\",\"You Never Give Me Your Money\",\"Sun King\",\"Mean Mr. Mustard\",\"Polythene Pam\",\"She Came In Through the Bathroom Window\",\"Golden Slumbers\",\"Carry That Weight\",\"The End\",\"Her Majesty\"]"
                        },
                        new
                        {
                            Id = 20,
                            Artist = "Nirvana",
                            Description = "The second studio album by American rock band Nirvana.",
                            Genre = "Grunge",
                            Name = "Nevermind",
                            Quantity = 10,
                            ReleaseDate = new DateOnly(1991, 9, 24),
                            TrackList = "[\"Smells Like Teen Spirit\",\"In Bloom\",\"Come as You Are\",\"Breed\",\"Lithium\",\"Polly\",\"Territorial Pissings\",\"Drain You\",\"Lounge Act\",\"Stay Away\",\"On a Plain\",\"Something in the Way\",\"Endless, Nameless\"]"
                        },
                        new
                        {
                            Id = 21,
                            Artist = "Dire Straits",
                            Description = "The fifth studio album by British rock band Dire Straits.",
                            Genre = "Roots Rock",
                            Name = "Brothers in Arms",
                            Quantity = 10,
                            ReleaseDate = new DateOnly(1985, 5, 13),
                            TrackList = "[\"So Far Away\",\"Money for Nothing\",\"Walk of Life\",\"Your Latest Trick\",\"Why Worry\",\"Ride Across the River\",\"The Man\\u0027s Too Strong\",\"One World\",\"Brothers in Arms\"]"
                        },
                        new
                        {
                            Id = 22,
                            Artist = "Pink Floyd",
                            Description = "The eleventh studio album by the English rock band Pink Floyd.",
                            Genre = "Progressive Rock",
                            Name = "The Wall",
                            Quantity = 10,
                            ReleaseDate = new DateOnly(1979, 11, 30),
                            TrackList = "[\"In the Flesh?\",\"The Thin Ice\",\"Another Brick in the Wall, Part 1\",\"The Happiest Days of Our Lives\",\"Another Brick in the Wall, Part 2\",\"Mother\",\"Goodbye Blue Sky\",\"Empty Spaces\",\"Young Lust\",\"One of My Turns\",\"Don\\u0027t Leave Me Now\",\"Another Brick in the Wall, Part 3\",\"Goodbye Cruel World\",\"Hey You\",\"Is There Anybody Out There?\",\"Nobody Home\",\"Vera\",\"Bring the Boys Back Home\",\"Comfortably Numb\",\"The Show Must Go On\",\"In the Flesh\",\"Run Like Hell\",\"Waiting for the Worms\",\"Stop\",\"The Trial\",\"Outside the Wall\"]"
                        },
                        new
                        {
                            Id = 23,
                            Artist = "Santana",
                            Description = "The eighteenth studio album by Latin rock band Santana.",
                            Genre = "Latin Rock",
                            Name = "Supernatural",
                            Quantity = 10,
                            ReleaseDate = new DateOnly(1999, 6, 15),
                            TrackList = "[\"(Da Le) Yaleo\",\"Love of My Life\",\"Put Your Lights On\",\"Africa Bamba\",\"Smooth\",\"Do You Like the Way\",\"Maria Maria\",\"Migra\",\"Coraz\\u00F3n Espinado\",\"Wishing It Was\",\"El Farol\",\"Primavera\",\"The Calling\"]"
                        },
                        new
                        {
                            Id = 24,
                            Artist = "Guns N' Roses",
                            Description = "The debut studio album by American hard rock band Guns N' Roses.",
                            Genre = "Hard Rock",
                            Name = "Appetite for Destruction",
                            Quantity = 10,
                            ReleaseDate = new DateOnly(1987, 7, 21),
                            TrackList = "[\"Welcome to the Jungle\",\"It\\u0027s So Easy\",\"Nightrain\",\"Out ta Get Me\",\"Mr. Brownstone\",\"Paradise City\",\"My Michelle\",\"Think About You\",\"Sweet Child o\\u0027 Mine\",\"You\\u0027re Crazy\",\"Anything Goes\",\"Rocket Queen\"]"
                        },
                        new
                        {
                            Id = 25,
                            Artist = "ABBA",
                            Description = "A compilation album by the Swedish pop group ABBA.",
                            Genre = "Pop, Disco",
                            Name = "Gold: Greatest Hits",
                            Quantity = 10,
                            ReleaseDate = new DateOnly(1992, 9, 21),
                            TrackList = "[\"Dancing Queen\",\"Knowing Me, Knowing You\",\"Take a Chance on Me\",\"Mamma Mia\",\"Lay All Your Love on Me\",\"Super Trouper\",\"I Have a Dream\",\"The Winner Takes It All\",\"Money, Money, Money\",\"SOS\",\"Chiquitita\",\"Fernando\",\"Voulez-Vous\",\"Gimme! Gimme! Gimme! (A Man After Midnight)\",\"Does Your Mother Know\",\"One of Us\",\"The Name of the Game\",\"Thank You for the Music\",\"Waterloo\"]"
                        },
                        new
                        {
                            Id = 26,
                            Artist = "Bon Jovi",
                            Description = "The third studio album by American rock band Bon Jovi.",
                            Genre = "Hard Rock, Glam Metal",
                            Name = "Slippery When Wet",
                            Quantity = 10,
                            ReleaseDate = new DateOnly(1986, 8, 18),
                            TrackList = "[\"Let It Rock\",\"You Give Love a Bad Name\",\"Livin\\u0027 on a Prayer\",\"Social Disease\",\"Wanted Dead or Alive\",\"Raise Your Hands\",\"Without Love\",\"I\\u0027d Die for You\",\"Never Say Goodbye\",\"Wild in the Streets\"]"
                        },
                        new
                        {
                            Id = 27,
                            Artist = "Boston",
                            Description = "The debut studio album by American rock band Boston.",
                            Genre = "Hard Rock",
                            Name = "Boston",
                            Quantity = 10,
                            ReleaseDate = new DateOnly(1976, 8, 25),
                            TrackList = "[\"More Than a Feeling\",\"Peace of Mind\",\"Foreplay/Long Time\",\"Rock \\u0026 Roll Band\",\"Smokin\\u0027\",\"Hitch a Ride\",\"Something About You\",\"Let Me Take You Home Tonight\"]"
                        },
                        new
                        {
                            Id = 28,
                            Artist = "Linkin Park",
                            Description = "The debut studio album by American rock band Linkin Park.",
                            Genre = "Nu Metal, Rap Rock",
                            Name = "Hybrid Theory",
                            Quantity = 10,
                            ReleaseDate = new DateOnly(2000, 10, 24),
                            TrackList = "[\"Papercut\",\"One Step Closer\",\"With You\",\"Points of Authority\",\"Crawling\",\"Runaway\",\"By Myself\",\"In the End\",\"A Place for My Head\",\"Forgotten\",\"Cure for the Itch\",\"Pushing Me Away\"]"
                        },
                        new
                        {
                            Id = 29,
                            Artist = "Bob Marley and the Wailers",
                            Description = "A compilation album by Bob Marley and the Wailers.",
                            Genre = "Reggae",
                            Name = "Legend",
                            Quantity = 10,
                            ReleaseDate = new DateOnly(1984, 5, 8),
                            TrackList = "[\"Is This Love\",\"No Woman, No Cry\",\"Could You Be Loved\",\"Three Little Birds\",\"Buffalo Soldier\",\"Get Up, Stand Up\",\"Stir It Up\",\"Easy Skanking\",\"One Love/People Get Ready\",\"I Shot the Sheriff\",\"Waiting in Vain\",\"Redemption Song\",\"Satisfy My Soul\",\"Exodus\",\"Jamming\",\"Punky Reggae Party\"]"
                        },
                        new
                        {
                            Id = 30,
                            Artist = "Metallica",
                            Description = "The fifth studio album by American heavy metal band Metallica.",
                            Genre = "Heavy Metal",
                            Name = "Metallica (The Black Album)",
                            Quantity = 10,
                            ReleaseDate = new DateOnly(1991, 8, 12),
                            TrackList = "[\"Enter Sandman\",\"Sad but True\",\"Holier Than Thou\",\"The Unforgiven\",\"Wherever I May Roam\",\"Don\\u0027t Tread on Me\",\"Through the Never\",\"Nothing Else Matters\",\"Of Wolf and Man\",\"The God That Failed\",\"My Friend of Misery\",\"The Struggle Within\"]"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
